### PR TITLE
Let's collaborate to make tomlj better

### PR DESCRIPTION
**Pull request by Dauthjan**
**_Fixes_** for #1 #2 and #3  

**Additional**: JSON is now created as per sequence of TOML and is now validated after creation. On invalid JSON creation, `JSONException` is thrown immediately.

**Additional**: Added new `parse()` methods with boolean parameter _( which decides the behavior of `parse()` )_. Default `parse()` methods will pass "**false**" (_existing functionality of parser_). New methods can have additional parameter set as: 
- _true_:  Throws Parsing issue immediately
- _false_: Default behaviour of the parser

**Additional**: `toMap()` does not drills deep in complex data types. However, if needed a complete Map of TOML, `toJsonPath()` creates it with <JSONPath, Value>, (maintains sequence as per TOML definition). Below is an example to what it does!

_Sample TOML:_
```
[table.subtable1]
  key                 = "table.subtable1 - another value"
  site."google.com"   = "table.subtable1 - site.\"google.com\""
  'quoted "value"'    = 'table.subtable1 - quoted "value"'
  site.'facebook.com' = "table.subtable1 - site.'facebook.com'"

[table."subtable 2"]
  key                 = "table.\"subtable 2\" - another value"
  site."google.com"   = "table.\"subtable 2\" - site.\"google.com\""
  'quoted "value"'    = 'table.\"subtable 2\" - quoted "value"'
  site.'facebook.com' = "table.\"subtable 2\" - site.'facebook.com'"

[table.'subtable 3']
  key                   = "table.\"subtable 3\" - another value"
  site . "google.com"   = "table.\"subtable 3\" - site.\"google.com\""
  'quoted "value"'      = 'table.\"subtable 3\" - quoted "value"'
  site . 'facebook.com' = "table.\"subtable 3\" - site.'facebook.com'"
  
[array]
key1 = [ 1, 2, 3 ]
key2 = [ "red", "yellow", "green" ]
key3 = [ [ 1, 2 ], [3, 4, 5] ]
key4 = [ [ 1, 2 ], ["a", "b", "c"] ] # this is ok

[[fruit]]
name = "apple"

[fruit.physical]
color = "red"
shape = "round"

[[fruit.variety]]
name = "red delicious"

[[fruit.variety]]
  name = "granny smith"

[[fruit]]
name = "banana"

[[fruit.variety]]
name = "plantain"
```
_Map created:_
```
$.[table].[subtable1].[key] => table.subtable1 - another value
$.[table].[subtable1].[site].[google.com] => table.subtable1 - site."google.com"
$.[table].[subtable1].[site].[facebook.com] => table.subtable1 - site.'facebook.com'
$.[table].[subtable1].[quoted "value"] => table.subtable1 - quoted "value"
$.[table].[subtable 2].[key] => table."subtable 2" - another value
$.[table].[subtable 2].[site].[google.com] => table."subtable 2" - site."google.com"
$.[table].[subtable 2].[site].[facebook.com] => table."subtable 2" - site.'facebook.com'
$.[table].[subtable 2].[quoted "value"] => table.\"subtable 2\" - quoted "value"
$.[table].[subtable 3].[key] => table."subtable 3" - another value
$.[table].[subtable 3].[site].[google.com] => table."subtable 3" - site."google.com"
$.[table].[subtable 3].[site].[facebook.com] => table."subtable 3" - site.'facebook.com'
$.[table].[subtable 3].[quoted "value"] => table.\"subtable 3\" - quoted "value"
$.[array].[key1][0] => 1
$.[array].[key1][1] => 2
$.[array].[key1][2] => 3
$.[array].[key2][0] => red
$.[array].[key2][1] => yellow
$.[array].[key2][2] => green
$.[array].[key3][0][0] => 1
$.[array].[key3][0][1] => 2
$.[array].[key3][1][0] => 3
$.[array].[key3][1][1] => 4
$.[array].[key3][1][2] => 5
$.[array].[key4][0][0] => 1
$.[array].[key4][0][1] => 2
$.[array].[key4][1][0] => a
$.[array].[key4][1][1] => b
$.[array].[key4][1][2] => c
$.[fruit][0].[name] => apple
$.[fruit][0].[physical].[color] => red
$.[fruit][0].[physical].[shape] => round
$.[fruit][0].[variety][0].[name] => red delicious
$.[fruit][0].[variety][1].[name] => granny smith
$.[fruit][1].[name] => banana
$.[fruit][1].[variety][0].[name] => plantain
```

**Experimental**: Enabled heterogeneous data types in array [originally added in [**TOML v1.0.0-rc.1**](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v1.0.0-rc.1.md)] (will be rolled back with introduction of version rules as per coding standards) :wink:

**Experimental**: Made Tomltype.typeNameFor "public" (useful in some cases) [used in my personal IBM Integration Bus project]

### CODE REVIEW

**Comment by cleishm** [comment]
Thanks for opening a pull request with these changes!

I don't see any test cases though? We should always start with a test that verifies the issues this PR is fixing.

**Comment by cleishm** [comment]
I just created and merged #6 as an example of a good pull request for this project. It has a test and addresses a specific issue or single improvement.

**Comment by Dauthjan** [comment]
Actually I'm new to Java and Git :sweat_smile:
This is the first time I'm working in Java. I will try to add some Test Cases to this however I am not very sure how much I'll be successful and how much time it will take.

I noticed your last commit to `JsonSerializer.java` however I feel one more escaping is needed.

```
if (ch == '\\') {
    out.append('\\');
    out.append('\\');
    continue;
}
```
TOML: `winpath  = 'C:\Users\nodejs\templates'`
JSON: `{"winpath": "C:\Users\nodejs\templates"}`

The JSON seems to be invalid as it expects `{"winpath": "C:\\Users\\nodejs\\templates"}`

Just a thought... I've already added this escape in my commit :slightly_smiling_face:
I'll try to give a Test Case asap! I really want this tomlj to be the best TOML lib in Java and planning to include TOML in my day-to-day development of IBM Integration Bus! Thanks a lot for your time!

**Comment by cleishm** [comment]
That sounds like a different issue from #1, and I'd be happy to see a failing test to demonstrate it!

**Comment by Dauthjan** [comment]
Hi @cleishm 
I just now added a [Test Case](https://github.com/Dauthjan/tomlj/blob/master/src/test/java/org/tomlj/JsonSerializer.java) for JsonSerializer. Is this something you are looking for?

**Comment by cleishm** [comment]
Yes, that test case is helpful. I split it out into #8. 

Generally, it's best to make each issue and PR address a discrete thing.

**Comment by Dauthjan** [comment]
I'll be learning a lot while working on it.. Thanks a lot

**Comment by cleishm** [comment]
I've implemented most of the fixes in separate PRs: #6,  #7, #8, #9 

Issue #4 remains, which I'd love a test case to demonstrate, and then we can look at how to resolve it.

**Comment by Dauthjan** [comment]
> Issue #4 remains, which I'd love a test case to demonstrate, and then we can look at how to resolve it.

[Here ](https://github.com/Dauthjan/tomlj/blob/master/src/test/java/org/tomlj/JsonSerializer.java)it is... hope it helps! Thanks a lot @cleishm  for your support!

**Comment by Dauthjan** [comment]
Updated the [TestCase ](https://github.com/Dauthjan/tomlj/blob/950f6a3cdcbe92aa2705aedb7664b00ac057d698/src/test/java/org/tomlj/JsonSerializer.java)just in case you need it.

**Comment by cleishm** [comment]
The last issue (#4) has been resolved by #10. I believe all the proposed changes have been incorporated! Thanks!

**Pull request closed without merging**
