### PR TITLE
Toml: Added arrayEquals() and tableEquals() methods with unit tests

### PR DESCRIPTION
**Pull request by kPYKx7Ddw4n1aIKZ**
Added arrayEquals() and tableEquals() methods with unit tests

### CODE REVIEW

**Comment by cleishm** [comment]
I'm unclear why these methods are static in the `Toml` class, rather than on `TomlTable` and `TomlArray`?

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
TomlTable and TomlArray are implemented as interface and one would have to define them as default methods.

However, this is not possible for the equals() method. (Also have a look [here](https://stackoverflow.com/questions/28019242/java-8-default-method-interface-override-object-equals-method).)

Another alternative would be to define the TomlTable and TomlArray interfaces as abstract classes.

**Comment by cleishm** [comment]
I don't know if it matters too much if they are interfaces vs ABC's. But thinking on it, there is probably good reasons to keep equals()/hashcode() based on object id rather than values.

**Comment by cleishm** [comment]
We just need to add some javadoc and we can merge this.

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
@cleishm I added javadoc.

**Pull request merged**
